version: '3.8'

services:
  bot:
    build: .
    container_name: second-brain-bot
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./token.json:/app/token.json
      - ./credentials.json:/app/credentials.json
